---

- include_tasks: variables.yml
- include_tasks: setup.yml

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: Проверка, что PostgreSQL будет запущен после загрузки
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml
