---
- name: Проверка что пакеты PostgreSQL установлены
  yum:
    name: "{{ postgresql_packages }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
    exclude: python-unversioned-command

- name: Проверка, что пакеты PostgreSQL Python libraries установлены
  yum:
    name: "{{ postgresql_python_library }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
